backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: config
    label: Config
    files:
      - name: config
        label: Config
        file: config.yaml
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: Site title
          - widget: hidden
            name: baseURL
            label: Base URL
            required: false
            hint: Hostname (and path) to the root
          - widget: object
            name: params
            label: Params
            required: true
            hint: Site parameters
            fields:
              - widget: image
                name: logo
                label: Logo
                required: true
                hint: the path of the logo image
              - widget: string
                name: docs_url
                label: Documentation Base URL
                required: true
                hint: the domain name of the external documentation site
          - widget: object
            name: menu
            label: Site Menus
            required: false
            hint: Menu items not related to a specific page
            fields:
              - widget: list
                name: main
                label: Main menu
                required: false
                hint: List of items for Main menu
                fields:
                  - widget: string
                    name: identifier
                    label: Identifier
                    required: true
                    hint: >-
                      The identifier of a menu item could be used as a parent
                      menu of another menu item
                  - widget: string
                    name: name
                    label: Title
                    required: true
                    hint: The title of the menu item
                  - widget: string
                    name: url
                    label: URL
                    required: true
                    hint: The URL the menu item links to
                  - widget: number
                    name: weight
                    label: Weight
                    required: false
                    hint: Position for sorting
                    valueType: int
                  - widget: string
                    name: parent
                    label: Parent Menu Identifier
                    required: false
                    hint: >-
                      The parent of an entry should be the identifier of another
                      entry.
              - widget: list
                name: secondary
                label: Secondary menu
                required: false
                hint: List of items for Secondary menu
                fields:
                  - widget: string
                    name: identifier
                    label: Identifier
                    required: true
                    hint: >-
                      The identifier of a menu item could be used as a parent
                      menu of another menu item
                  - widget: string
                    name: name
                    label: Title
                    required: true
                    hint: The title of the menu item
                  - widget: string
                    name: url
                    label: URL
                    required: true
                    hint: The URL the menu item links to
                  - widget: number
                    name: weight
                    label: Weight
                    required: false
                    hint: Position for sorting
                    valueType: int
                  - widget: string
                    name: parent
                    label: Parent Menu Identifier
                    required: false
                    hint: >-
                      The parent of an entry should be the identifier of another
                      entry.
          - widget: hidden
            name: disableKinds
            label: Disable Kinds
            required: false
            hint: Enable disabling of all pages of the specified Kinds.
          - widget: hidden
            name: uglyURLs
            label: Ugly URLs
            required: false
            hint: >-
              When enabled, creates URL of the form /filename.html instead of
              /filename/.
  - name: home
    label: Home
    files:
      - name: home
        label: Home
        file: content/_index.md
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: The title of the page.
          - widget: string
            name: heading
            label: Heading
            required: false
            hint: The heading displayed on the homepage
          - widget: boolean
            name: show_button
            label: Show Button
            required: false
            hint: Show or hide the button on the hompage
          - widget: string
            name: homepage_button_link
            label: Button URL
            required: false
            hint: Button link
          - widget: string
            name: homepage_button_text
            label: Button Text
            required: false
            hint: Text displayed in the button
          - widget: object
            name: menu
            label: Home Menus
            required: false
            hint: Which menus should this page show up in
            fields:
              - widget: object
                name: main
                label: Main menu item
                required: false
                hint: Main menu item for this page
                fields:
                  - widget: string
                    name: name
                    label: Title
                    required: false
                    hint: The title of the menu item
                  - widget: number
                    name: weight
                    label: Weight
                    required: false
                    hint: Position for sorting
                    valueType: int
                  - widget: string
                    name: identifier
                    label: Identifier
                    required: false
                    hint: >-
                      The identifier of a menu item could be used as a parent
                      menu of another menu item
                  - widget: string
                    name: parent
                    label: Parent Menu Identifier
                    required: false
                    hint: >-
                      The parent of an entry should be the identifier of another
                      entry.
              - widget: object
                name: secondary
                label: Secondary menu item
                required: false
                hint: Secondary menu item for this page
                fields:
                  - widget: string
                    name: name
                    label: Title
                    required: false
                    hint: The title of the menu item
                  - widget: number
                    name: weight
                    label: Weight
                    required: false
                    hint: Position for sorting
                    valueType: int
                  - widget: string
                    name: identifier
                    label: Identifier
                    required: false
                    hint: >-
                      The identifier of a menu item could be used as a parent
                      menu of another menu item
                  - widget: string
                    name: parent
                    label: Parent Menu Identifier
                    required: false
                    hint: >-
                      The parent of an entry should be the identifier of another
                      entry.
          - widget: hidden
            name: layout
            label: Layout
            required: true
            default: home
          - widget: markdown
            name: body
            label: Content
            required: false
            hint: Page content
  - name: links
    label: Supported Platforms
    files:
      - name: links
        label: Supported Platforms
        file: data/links.json
        fields:
          - widget: list
            name: ssg
            label: Static Site Generators
            required: false
            hint: A list of static site generators supported by Stackbit
            fields:
              - widget: string
                name: title
                label: Title
                required: true
              - widget: string
                name: url
                label: URL
                required: true
          - widget: list
            name: cms
            label: Headless CMS
            required: false
            hint: A list of headless CMS supported by Stackbit
            fields:
              - widget: string
                name: title
                label: Title
                required: true
              - widget: string
                name: url
                label: URL
                required: true
  - name: feature
    label: Features
    folder: content/features
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: The title of the page.
      - widget: string
        name: description
        label: Description
        required: false
        hint: The text shown just below the features title.
      - widget: image
        name: image_thumbnail
        label: Thumbnail Image
        required: false
        hint: The image shown in the feature.
      - widget: string
        name: button_link
        label: Button Link
        required: false
        hint: The button link
      - widget: string
        name: button_text
        label: Button Text
        required: false
        hint: The button text
      - widget: object
        name: menu
        label: Feature Menus
        required: false
        hint: Which menus should this page show up in
        fields:
          - widget: object
            name: main
            label: Main menu item
            required: false
            hint: Main menu item for this page
            fields:
              - widget: string
                name: name
                label: Title
                required: false
                hint: The title of the menu item
              - widget: number
                name: weight
                label: Weight
                required: false
                hint: Position for sorting
                valueType: int
              - widget: string
                name: identifier
                label: Identifier
                required: false
                hint: >-
                  The identifier of a menu item could be used as a parent menu
                  of another menu item
              - widget: string
                name: parent
                label: Parent Menu Identifier
                required: false
                hint: >-
                  The parent of an entry should be the identifier of another
                  entry.
          - widget: object
            name: secondary
            label: Secondary menu item
            required: false
            hint: Secondary menu item for this page
            fields:
              - widget: string
                name: name
                label: Title
                required: false
                hint: The title of the menu item
              - widget: number
                name: weight
                label: Weight
                required: false
                hint: Position for sorting
                valueType: int
              - widget: string
                name: identifier
                label: Identifier
                required: false
                hint: >-
                  The identifier of a menu item could be used as a parent menu
                  of another menu item
              - widget: string
                name: parent
                label: Parent Menu Identifier
                required: false
                hint: >-
                  The parent of an entry should be the identifier of another
                  entry.
      - widget: hidden
        name: layout
        label: Layout
        required: true
        default: feature
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
    filter:
      field: layout
      value: feature
  - name: features
    label: Featuress
    folder: content/
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: The title of the page.
      - widget: object
        name: menu
        label: Features Menus
        required: false
        hint: Which menus should this page show up in
        fields:
          - widget: object
            name: main
            label: Main menu item
            required: false
            hint: Main menu item for this page
            fields:
              - widget: string
                name: name
                label: Title
                required: false
                hint: The title of the menu item
              - widget: number
                name: weight
                label: Weight
                required: false
                hint: Position for sorting
                valueType: int
              - widget: string
                name: identifier
                label: Identifier
                required: false
                hint: >-
                  The identifier of a menu item could be used as a parent menu
                  of another menu item
              - widget: string
                name: parent
                label: Parent Menu Identifier
                required: false
                hint: >-
                  The parent of an entry should be the identifier of another
                  entry.
          - widget: object
            name: secondary
            label: Secondary menu item
            required: false
            hint: Secondary menu item for this page
            fields:
              - widget: string
                name: name
                label: Title
                required: false
                hint: The title of the menu item
              - widget: number
                name: weight
                label: Weight
                required: false
                hint: Position for sorting
                valueType: int
              - widget: string
                name: identifier
                label: Identifier
                required: false
                hint: >-
                  The identifier of a menu item could be used as a parent menu
                  of another menu item
              - widget: string
                name: parent
                label: Parent Menu Identifier
                required: false
                hint: >-
                  The parent of an entry should be the identifier of another
                  entry.
      - widget: hidden
        name: layout
        label: Layout
        required: true
        default: features
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
    filter:
      field: layout
      value: features
  - name: about
    label: Abouts
    folder: content/
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - widget: string
        name: title
        label: Title
        required: true
        hint: The title of the page.
      - widget: object
        name: menu
        label: About Menus
        required: false
        hint: Which menus should this page show up in
        fields:
          - widget: object
            name: main
            label: Main menu item
            required: false
            hint: Main menu item for this page
            fields:
              - widget: string
                name: name
                label: Title
                required: false
                hint: The title of the menu item
              - widget: number
                name: weight
                label: Weight
                required: false
                hint: Position for sorting
                valueType: int
              - widget: string
                name: identifier
                label: Identifier
                required: false
                hint: >-
                  The identifier of a menu item could be used as a parent menu
                  of another menu item
              - widget: string
                name: parent
                label: Parent Menu Identifier
                required: false
                hint: >-
                  The parent of an entry should be the identifier of another
                  entry.
          - widget: object
            name: secondary
            label: Secondary menu item
            required: false
            hint: Secondary menu item for this page
            fields:
              - widget: string
                name: name
                label: Title
                required: false
                hint: The title of the menu item
              - widget: number
                name: weight
                label: Weight
                required: false
                hint: Position for sorting
                valueType: int
              - widget: string
                name: identifier
                label: Identifier
                required: false
                hint: >-
                  The identifier of a menu item could be used as a parent menu
                  of another menu item
              - widget: string
                name: parent
                label: Parent Menu Identifier
                required: false
                hint: >-
                  The parent of an entry should be the identifier of another
                  entry.
      - widget: hidden
        name: layout
        label: Layout
        required: true
        default: basic
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
    filter:
      field: layout
      value: basic
